### PR TITLE
SpecCompose Implementation

### PR DESCRIPTION
**Pull request by omerferhatt**
- BaseCompose class added
- Compose class inherited from BaseCompose
- SpecCompose class created according to magnitude spectrogram
- SpecCompose unit test added

### CODE REVIEW

**Comment by omerferhatt** [comment]
According to #66 issue

**Comment by iver56** [comment]
Thanks for the PR! I'll have a look

**Comment by iver56** [comment]
The only remark I have is that we need to import `SpecCompose` in audiomentations/\_\_init\_\_.py. `Compose` is also imported there. This makes the class easily importable for people who have install the audiomentations package.

**Comment by omerferhatt** [comment]
I added to __init__ in audiomentations. is there anything that I need to fix ?

**Comment by iver56** [comment]
Thanks

**Pull request merged**
