### PR TITLE
Add Limiter transform

### LINKED ISSUE #11: Add dynamic range compression transformation

### PR DESCRIPTION
**Pull request by iver56**
Close #11

- [x] Check if inplace is faster
- [x] Mention the Limiter in readme
- [x] Wait for cylimiter release with Windows support

### CODE REVIEW

**Comment by pzelasko** [comment]
Looks good! I like the work on defining the thresholds in dBs, maybe I should support that too at some point.

**Comment by pzelasko** [comment]
The new release with your fixes is available here https://pypi.org/project/cylimiter/0.2.1/

**Comment by iver56** [comment]
inplace: 2.818 s (std: 0.048 s)
copy: 6.612 s (std: 0.141 s)

inplace it is then! I'm glad I checked :)

**Comment by pzelasko** [comment]
It seems like I didn't do enough testing of the Python wrapper part -- will fix and let you know once it's working again.

**Comment by pzelasko** [comment]
Okay, this should work now, it's also 5x faster 😅 

https://pypi.org/project/cylimiter/0.3.0/

**Comment by iver56** [comment]
Good work :) I [upgraded to cylimiter to 0.3.0 and switched to the inplace function](https://github.com/iver56/audiomentations/commit/74f35666a74af6cb29f2b0435e1946bf467650c0), and I measured a ~8x speedup!

**Pull request merged**
