### PR TITLE
Add TanhDistortion

### PR DESCRIPTION
**Pull request by atamazian**
Adds TanhDistortion according to https://github.com/iver56/audiomentations/issues/50

### CODE REVIEW

**Comment by iver56** [comment]
Thanks for the initiative :) This is a good start. Here are some thoughts on how it can be improved further:

* Have a mechanism that randomly varies `c2` between a specified min value and max value
* Remove the `c1` parameter and have it calculated automatically on the fly so that the RMS of the input and the output becomes the same (AKA post gain / gain compensation)

What do you think?

**Comment by atamazian** [comment]
Your suggestions look quite good, I'll try to implement them.

**Comment by atamazian** [comment]
I've implemented all things you mentioned, however, I wasn't able to make RMS of transformed and original signal completely equal - they're equal if rounded up to 3 decimals.

**Comment by iver56** [comment]
LGTM. Thanks for the contribution :) Note that I may do some minor changes later, some time before a new version of audiomentations with the new transform gets released

**Pull request merged**
