### PR TITLE
Add Distortion transformation

### LINKED ISSUE #5: Add distortion transformation

### PR DESCRIPTION
**Pull request by askskro**
Adds a very simple distortion transformation.

Closes #5

### CODE REVIEW

**Comment by iver56** [comment]
Thanks for the contribution!

Here are my thoughts thus far: It's not obvious from the parameter name docstring that the actual percentile is selected randomly. Perhaps it can be made more obvious by having _two_ parameters min_percentile_threshold and max_percentile_threshold instead of a single parameter percentile_cut_off. I would rather call it threshold than cutoff to avoid confusion, since cutoff is usually a term used for a parameter you can tweak to change the frequency response of a low-pass/high-pass filter.

**Comment by iver56** [comment]
Also, perhaps it's best to rename the class to `ClippingDistortion`, since many other kinds of distortion also exist?

**Comment by askskro** [comment]
Thanks for the feedback. Suggested changes have been made.

**Comment by iver56** [comment]
Nice!

**Pull request merged**
