### PR TITLE
Add Resample and Downsample transforms

### LINKED ISSUE #6: Add downsampling transformation

### PR DESCRIPTION
**Pull request by askskro**
Add Resample and Downsample transforms with tests and demo usage.
Closes #6 
Feedback requested on default values for min and max sampling range.

### CODE REVIEW

**Comment by iver56** [comment]
max_sample_rate=44100 (CD quality) seems like an apt default

**Comment by iver56** [comment]
I think we can remove `Downsample` and make do with `Resample`. We could add to the `Resample` docstring that it can be used for downsampling by specifying small min_sample_rate and max_sample_rate

**Comment by askskro** [comment]
Thanks for the feedback. Changes made.

**Comment by iver56** [comment]
Thanks! ⭐️ 🥇

**Pull request merged**
