### PR TITLE
Add __repr__ similar to albumentations

### PR DESCRIPTION
**Pull request by atamazian**
Attempt to implement https://github.com/iver56/audiomentations/issues/285.

### CODE REVIEW

**Comment by atamazian** [comment]
I see your point, will try to implement.

**Comment by atamazian** [comment]
I was simply following `albumentations` syntax.

**Comment by atamazian** [comment]
I've used `inspect` to replace `get_transform_init_args_names`. Is this better? As for the test, I used a simple script to check this. When you approve final `__repr__` realization, I'll write an "official" test for this.

**Comment by iver56** [comment]
Yeah, that's better. You went from adding 500 lines to adding just 200 lines. That feels more manageable.

I gave the repr a try, and I like the style in which it represents objects. You can start writing an "official" test for this.

During my testing, I uncovered an issue. What I did was I added a `print(augmenter)` in the loop in demo/demo.py and tried to run it. I ran into multiple exceptions, for example:

'AddBackgroundNoise' object has no attribute 'sounds_path'
'ApplyImpulseResponse' object has no attribute 'ir_path'
'AddShortNoises' object has no attribute 'sounds_path'
'AdjustDuration' object has no attribute 'duration_samples'
'Aliasing' object has no attribute 'min_sample_rate'
'SevenBandParametricEQ' object has no attribute 'min_gain_db'

The problem seems to be that the __repr__ tries to access attributes that do not exist, resulting in an exception. Apparently, our current test suite did not catch all these issues.

I guess we need to
1) add missing attributes
2) tolerate missing attribute instead of throwing an exception - this would feel a little bit safer in case we miss some cases

**Comment by atamazian** [comment]
I'm glad to hear you liked it! I'll modify the code accordingly.

**Comment by atamazian** [comment]
I've made some modifications to the code. Is it better now?

**Comment by iver56** [comment]
Yes

**Comment by atamazian** [comment]
I'm not sure how a test should look like for `__repr__`. Should I compare two strings? Or where is a better way of doing it?

**Comment by iver56** [comment]
Something like

```
transform = Compose([GainTransition(), Shift()])
assert str(transform) == "whatever it is supposed to be"
```

**Comment by iver56** [comment]
Neat! Thanks for the contribution

**Pull request merged**
